analyzer:
  errors:
    invalid_annotation_target: ignore
    must_be_immutable: ignore
    unused_catch_clause: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    cancel_subscriptions: true