targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          ignore_unannotated: false
          include_if_null: true