name: vk_music
description: Free music client.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.3.1+20251206

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #UI
  audio_video_progress_bar: ^2.0.1
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.9

  just_audio_background: ^0.0.1-beta.17
  just_audio: ^0.10.4
  elementary: ^3.1.2
  elementary_helper: ^1.0.2
  dio: ^5.7.0
  retrofit: ^4.7.2
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  auto_route: ^10.1.2
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  system_theme: ^3.1.2
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  collection: ^1.19.1
  mask_text_input_formatter: ^2.9.0
  text_marquee: ^0.0.2
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new: ^3.2.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  device_info_plus: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  hive_ce_generator: ^1.9.3
  auto_route_generator: ^10.2.4
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  lean_builder: ^0.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
